"use client";
import { useEffect, useState } from 'react';
import { PortalDialog } from './portal-dialog';
import { BulkAccessEditor } from './bulk-access-editor';
import { supabase } from '../lib/supabase';
type Settings = { defaults?: string[]; optional?: string[]; allow?: string[]; deny?: string[]; publish?: string; edit_apps?: boolean | null };
type User = { id: string; name: string; email: string; role: string; department: string | null; updated_at: string; effective: { catalog: string[] } };
type Rule = { subject_type: string; subject_key: string; revision: number; settings: Settings };
type Data = { users: User[]; apps: { id: string; name: string }[]; departments: string[]; rules: Rule[] };
export function AccessManagement({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
 const [data,setData]=useState<Data|null>(null), [error,setError]=useState(''), [message,setMessage]=useState('');
 const [type,setType]=useState('user'), [key,setKey]=useState(''), [search,setSearch]=useState('');
 const [settings,setSettings]=useState<Settings>({}), [role,setRole]=useState('employee'), [department,setDepartment]=useState('');
 const [busy,setBusy]=useState(false), [review,setReview]=useState(false);
 const load=async()=>{ const result=await supabase?.rpc('get_portal_access_management'); if(result?.error) {setError('Unable to load access settings. Please refresh or contact your administrator.');return;} if(result?.data) {setData(result.data);setError('');} };
 useEffect(()=>{ let current=true; supabase?.rpc('get_portal_access_management').then(({data,error})=>{if(!current)return;if(error)setError('Unable to load access settings.');else setData(data);});return()=>{current=false;};},[]);
 const choose=(nextType:string,nextKey:string)=>{setType(nextType);setKey(nextKey);setReview(false);setError('');setMessage('');const rule=data?.rules.find(r=>r.subject_type===nextType&&r.subject_key===nextKey);setSettings(rule?.settings||{});const u=data?.users.find(u=>u.id===nextKey);setRole(u?.role||'employee');setDepartment(u?.department||'');};
 const setApp=(id:string,value:string)=>{const a=type==='user'?'allow':'defaults',b=type==='user'?'deny':'optional';setSettings(current=>({...current,[a]:[...(current[a]||[]).filter(x=>x!==id),...(value===a?[id]:[])],[b]:[...(current[b]||[]).filter(x=>x!==id),...(value===b?[id]:[])]}));setReview(false);};
 const save=async()=>{if(!data||!supabase)return;setBusy(true);setError('');const rule=data.rules.find(r=>r.subject_type===type&&r.subject_key===key);const user=data.users.find(u=>u.id===key);const {error}=await supabase.rpc('save_portal_access',{subject_type_in:type,subject_key_in:key,settings_in:settings,expected_revision:rule?.revision||0,profile_role:type==='user'?role:null,profile_department:type==='user'?department:null,expected_profile_updated_at:type==='user'?user?.updated_at:null});setBusy(false);if(error){setError(error.code==='40001'?'Someone changed these settings. Reload, select this person or group again, and reapply your changes.':'The changes could not be saved. Check your access and try again.');return;}await load();setReview(false);setMessage('Access settings saved. Affected users should refresh their portal.');onSaved();};
 const user=data?.users.find(u=>u.id===key);
 const inheritedApps=new Set(data?.rules.filter(r=>(r.subject_type==='role'&&r.subject_key===role)||(r.subject_type==='department'&&r.subject_key===department)).flatMap(r=>[...(r.settings.defaults||[]),...(r.settings.optional||[])])||[]);
 const title=type==='user'?(user?.name||user?.email||'Employee'):key;
 return <PortalDialog title="Access management" onClose={onClose} busy={busy}><section className="access-management"><div className="shared-editor-heading"><div><h1>Access management</h1><p>Manage portal roles, departments, and app visibility.</p></div><button disabled={busy} onClick={onClose} aria-label="Close access management">×</button></div>
 {error&&<p role="alert">{error}<button onClick={load}>Reload</button></p>}{message&&<p role="status">{message}</p>}
 {!data?<p>{error ? "Access settings are unavailable." : "Loading access settings…"}</p>:<><div className="access-modes">{[['user','Employees'],['bulk','Bulk edit'],['role','Role defaults'],['department','Department defaults']].map(([value,label])=><button key={value} aria-pressed={type===value} disabled={busy} onClick={()=>choose(value,'')}>{label}</button>)}</div><AccessGuide />{type==='bulk'?<BulkAccessEditor data={data} onBusy={setBusy} onSaved={async()=>{await load();onSaved();}} />:<div className="access-layout"><aside><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, email, or department"/></label>{type==='user'&&<p>Employees appear after their first portal sign-in.</p>}<div className="access-subjects">{(type==='user'?data.users.filter(u=>`${u.name} ${u.email}`.toLowerCase().includes(search.toLowerCase())).map(u=>({id:u.id,label:u.name||u.email,detail:u.email})): (type==='role'?['employee','manager','admin']:data.departments).filter(x=>x.toLowerCase().includes(search.toLowerCase())).map(x=>({id:x,label:x,detail:''}))).map(item=><button key={item.id} disabled={busy} aria-pressed={key===item.id} onClick={()=>choose(type,item.id)}><strong>{item.label}</strong><small>{item.detail}</small></button>)}</div></aside><div>{!key?<p>Select an employee, role, or department to manage access.</p>:<><h2>{title}</h2>{type==='user'&&<div className="access-profile"><label>Role<select disabled={busy} value={role} onChange={e=>{setRole(e.target.value);setReview(false);}}>{['employee','manager','admin'].map(r=><option key={r}>{r}</option>)}</select></label><label>Department<select disabled={busy} value={department} onChange={e=>{setDepartment(e.target.value);setReview(false);}}><option value="">Unassigned</option>{data.departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Publish company updates<select disabled={busy} value={settings.publish||'inherit'} onChange={e=>{setSettings({...settings,publish:e.target.value});setReview(false);}}><option value="inherit">Use role and department</option><option value="none">Cannot publish</option><option value="department">Own department only</option><option value="company">Company-wide</option></select></label><label>Edit shared apps<select disabled={busy} value={settings.edit_apps==null?'inherit':String(settings.edit_apps)} onChange={e=>{setSettings({...settings,edit_apps:e.target.value==='inherit'?null:e.target.value==='true'});setReview(false);}}><option value="inherit">Use existing editor permission</option><option value="true">Allow</option><option value="false">Deny</option></select></label></div>}
 <p>{type==='user'?'Use role/department keeps inherited access. Allow adds an app; Deny blocks it even if their role or department allows it.':'Default apps are included automatically. Optional apps appear in the directory. Not included removes this group’s grant; another role or department may still grant access.'}</p>
 <div className="access-apps">{data.apps.map(app=><label key={app.id}><span>{app.name}</span><select disabled={busy} value={(type==='user'?settings.allow:settings.defaults)?.includes(app.id)?(type==='user'?'allow':'defaults'):(type==='user'?settings.deny:settings.optional)?.includes(app.id)?(type==='user'?'deny':'optional'):'inherit'} onChange={e=>setApp(app.id,e.target.value)}><option value="inherit">{type==='user'?`Use role/department · ${inheritedApps.has(app.id)?'Allowed':'Not allowed'}`:'Not included'}</option><option value={type==='user'?'allow':'defaults'}>{type==='user'?'Allow':'Default app'}</option><option value={type==='user'?'deny':'optional'}>{type==='user'?'Deny':'Optional app'}</option></select></label>)}</div>
 {review&&<div className="access-review"><strong>Apply these settings to {title}?</strong><p>{type==='user'?`Role: ${role}. Department: ${department||'Unassigned'}.`:'This changes the app defaults for everyone in this group.'}</p><p>{type==='user'&&`Publishing: ${settings.publish||'Use role and department'}. Shared app editing: ${settings.edit_apps==null?'Use existing permission':settings.edit_apps?'Allow':'Deny'}.`}</p><p>Allow/default: {data.apps.filter(a=>(settings.allow||settings.defaults||[]).includes(a.id)).map(a=>a.name).join(', ')||'None'}</p><p>Deny/optional: {data.apps.filter(a=>(settings.deny||settings.optional||[]).includes(a.id)).map(a=>a.name).join(', ')||'None'}</p></div>}
 <button className="primary" disabled={busy} onClick={()=>review?void save():setReview(true)}>{busy?'Saving…':review?'Save access changes':'Review changes'}</button></>}</div></div>}</>}
 </section></PortalDialog>;
}

function AccessGuide() {
 return <details className="access-guide"><summary>What do the different access settings mean?</summary><dl>
 <dt>Employee</dt><dd>Uses employee app defaults. Cannot publish updates unless a department rule or individual permission allows it.</dd>
 <dt>Manager</dt><dd>Uses manager app defaults and can publish to their own department when assigned. This role alone does not mean the Management department.</dd>
 <dt>Admin</dt><dd>Uses admin app defaults and can publish company-wide. Changing other people’s permissions still requires separate Access management permission.</dd>
 <dt>Department</dt><dd>Adds that department’s apps to the role defaults. Management also grants company-wide publishing. Training Team’s initial extra app is Talent Director.</dd>
 <dt>Default / Optional</dt><dd>Default apps join the person’s apps automatically. Optional apps are available to add from the directory. Pinning is a separate personal choice.</dd>
 <dt>Allow / Deny / Use role and department</dt><dd>Allow grants a specific app. Deny blocks it even when a role or department grants it. Use role and department removes the individual exception.</dd>
 <dt>Publishing</dt><dd>Controls whether updates can be published to nobody, the person’s own department, or the whole company. It does not grant app editing.</dd>
 <dt>Edit company apps</dt><dd>Allows changes to shared app names, descriptions, links, and logos. It does not grant permission to edit people’s access.</dd>
 <dt>Access management</dt><dd>Allows changing people’s roles and permissions. This is separately restricted to approved access managers.</dd>
 </dl></details>;
}
